version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pkm_postgres
    restart: always
    environment:
      POSTGRES_USER: pkm_user
      POSTGRES_PASSWORD: pkm_password
      POSTGRES_DB: pkm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
