services:
  postgres:
    image: postgres:15
    container_name: pkm_postgres
    restart: always
    environment:
      POSTGRES_USER: pkm_user
      POSTGRES_PASSWORD: pkm_password
      POSTGRES_DB: pkm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  joplin-server:
    image: joplin/server:latest
    container_name: pkm_joplin_server
    restart: always
    depends_on:
      - postgres
    ports:
      - "22300:22300"
    environment:
      APP_PORT: 22300
      DB_CLIENT: pg
      POSTGRES_PASSWORD: pkm_password
      POSTGRES_DATABASE: pkm_db
      POSTGRES_USER: pkm_user
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:22300/api/ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
