/**
 * PKM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Folder { 
    /**
     * The unique identifier for the folder
     */
    id: string;
    /**
     * The name of the folder
     */
    name: string;
    /**
     * The icon of the folder
     */
    icon?: string;
}

