/**
 * PKM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Note { 
    /**
     * The unique identifier for the note
     */
    id: string;
    /**
     * The title of the note
     */
    title: string;
    /**
     * The content of the note (markdown formatted)
     */
    content?: string;
    /**
     * The content of the note (html formatted)
     */
    'content-html'?: string;
    /**
     * The author of the note
     */
    author?: string;
    /**
     * The URL source of the note
     */
    source_url?: string;
    /**
     * The ID of the folder the note belongs to
     */
    folder?: string;
    /**
     * The timestamp when the note was created
     */
    created?: string;
    /**
     * The timestamp when the note was last updated
     */
    updated?: string;
}

